/**
 *
 * $Id$
 */
package de.hub.visualemf.modiscodata.validation;

import org.eclipse.emf.ecore.EObject;

/**
 * A sample validator interface for {@link de.hub.visualemf.modiscodata.MoDiscoDataItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MoDiscoDataItemValidator {
	boolean validate();

	boolean validateRepresentedElement(EObject value);
	boolean validateName(String value);
	boolean validateId(String value);
}
