/**
 *
 * $Id$
 */
package de.hub.visualemf.data.validation;

import de.hub.visualemf.data.DataItem;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EAttribute;

/**
 * A sample validator interface for {@link de.hub.visualemf.data.DataSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataSetValidator {
	boolean validate();

	boolean validateNameAttribute(EAttribute value);
	boolean validateIdAttribute(EAttribute value);
	boolean validateName(String value);

	boolean validateItems(EList<DataItem> value);
}
